// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.1
// source: unary.proto

package unary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ValueA int32 `protobuf:"varint,2,opt,name=value_a,json=valueA,proto3" json:"value_a,omitempty"`
	ValueB int32 `protobuf:"varint,3,opt,name=value_b,json=valueB,proto3" json:"value_b,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unary_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_unary_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_unary_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Req) GetValueA() int32 {
	if x != nil {
		return x.ValueA
	}
	return 0
}

func (x *Req) GetValueB() int32 {
	if x != nil {
		return x.ValueB
	}
	return 0
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin *Req  `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Answer int32 `protobuf:"varint,2,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unary_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_unary_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_unary_proto_rawDescGZIP(), []int{1}
}

func (x *Res) GetOrigin() *Req {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Res) GetAnswer() int32 {
	if x != nil {
		return x.Answer
	}
	return 0
}

var File_unary_proto protoreflect.FileDescriptor

var file_unary_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a,
	0x03, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x5f, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x41, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x62, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x22, 0x3b, 0x0a, 0x03,
	0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x52, 0x65, 0x71, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x32, 0x21, 0x0a, 0x05, 0x55, 0x6e, 0x61,
	0x72, 0x79, 0x12, 0x18, 0x0a, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x12, 0x04,
	0x2e, 0x52, 0x65, 0x71, 0x1a, 0x04, 0x2e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x75, 0x6e, 0x61, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_unary_proto_rawDescOnce sync.Once
	file_unary_proto_rawDescData = file_unary_proto_rawDesc
)

func file_unary_proto_rawDescGZIP() []byte {
	file_unary_proto_rawDescOnce.Do(func() {
		file_unary_proto_rawDescData = protoimpl.X.CompressGZIP(file_unary_proto_rawDescData)
	})
	return file_unary_proto_rawDescData
}

var file_unary_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_unary_proto_goTypes = []interface{}{
	(*Req)(nil), // 0: Req
	(*Res)(nil), // 1: Res
}
var file_unary_proto_depIdxs = []int32{
	0, // 0: Res.origin:type_name -> Req
	0, // 1: Unary.Multiply:input_type -> Req
	1, // 2: Unary.Multiply:output_type -> Res
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_unary_proto_init() }
func file_unary_proto_init() {
	if File_unary_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unary_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unary_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unary_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_unary_proto_goTypes,
		DependencyIndexes: file_unary_proto_depIdxs,
		MessageInfos:      file_unary_proto_msgTypes,
	}.Build()
	File_unary_proto = out.File
	file_unary_proto_rawDesc = nil
	file_unary_proto_goTypes = nil
	file_unary_proto_depIdxs = nil
}
